### PR TITLE
Added HGVS to Genomic Coordinate Converter. 

### LINKED ISSUE #4: Add support for HGVS coordinates
https://bitbucket.org/biocommons/hgvs

### PR DESCRIPTION
**Pull request by patmagee**
Fix #4

### CODE REVIEW

**Comment by mcupak** [comment]
@patmagee This breaks the CI (see above), can you please fix that? Missing Python and HGVS-related dependencies in `.travis.yml`.

Also I've noticed we have HG19("hg19", 19) and GRCH37("GRCh37", 37) now - how should we use the two?

**Comment by mcupak** [comment]
@patmagee Still failing.

**Comment by mcupak** [comment]
Any update @patmagee ? Has this been fixed in upstream?

**Comment by patmagee** [comment]
@mcupak It looks like they resolved the dependency issue already. All tests are now passing

**Pull request merged**
